# Generated by Django 4.2.7 on 2026-03-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HowItWorksStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200)),
                ('title_bn', models.CharField(blank=True, max_length=200)),
                ('description_en', models.TextField()),
                ('description_bn', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'How It Works Step',
                'verbose_name_plural': 'How It Works Steps',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LiveCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_en', models.CharField(max_length=100)),
                ('label_bn', models.CharField(blank=True, max_length=100)),
                ('value', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Live Counter',
                'verbose_name_plural': 'Live Counters',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
            },
        ),
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('features', 'Features'), ('pricing', 'Pricing'), ('contact', 'Contact'), ('blog', 'Blog'), ('faq', 'FAQ'), ('clients', 'Clients')], max_length=20, unique=True)),
                ('meta_title_en', models.CharField(blank=True, max_length=200)),
                ('meta_title_bn', models.CharField(blank=True, max_length=200)),
                ('meta_description_en', models.TextField(blank=True, max_length=500)),
                ('meta_description_bn', models.TextField(blank=True, max_length=500)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
            ],
            options={
                'verbose_name': 'Page SEO',
                'verbose_name_plural': 'Page SEO',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='BIDYATek', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('business_hours', models.CharField(blank=True, help_text='e.g. Sat-Thu, 9:00 AM - 6:00 PM', max_length=200)),
                ('facebook_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Include country code', max_length=20)),
                ('analytics_id', models.CharField(blank=True, help_text='Google Analytics 4 measurement ID', max_length=50)),
                ('video_embed_url', models.URLField(blank=True, help_text='YouTube or Vimeo embed URL for demo video')),
                ('newsletter_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
