# Generated by Django 4.2.7 on 2026-03-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('category', models.CharField(choices=[('dashboard', 'Dashboard'), ('student_panel', 'Student Panel'), ('teacher_panel', 'Teacher Panel'), ('mobile_app', 'Mobile App'), ('website_template', 'Website Template')], default='dashboard', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
