# Generated by Django 4.2.7 on 2026-03-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_tag_alter_blogpost_options_blogpost_excerpt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='author',
            new_name='author_en',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='excerpt',
            new_name='excerpt_bn',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_bn',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_en',
            field=models.TextField(blank=True),
        ),
    ]
