# Generated by Django 4.2.7 on 2026-03-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='schools/logos/')),
                ('location', models.CharField(max_length=200)),
                ('description_en', models.TextField(blank=True)),
                ('description_bn', models.TextField(blank=True)),
                ('testimonial_en', models.TextField(blank=True, help_text='Optional testimonial quote')),
                ('testimonial_bn', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('target_audience', models.CharField(help_text='e.g. Small schools', max_length=200)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
