# Generated by Django 4.2.7 on 2026-03-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_bn', models.CharField(blank=True, max_length=100)),
                ('description_en', models.TextField()),
                ('description_bn', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='modules/icons/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('target_audience', models.CharField(help_text='e.g. Small schools', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=10)),
                ('support_type', models.CharField(help_text='e.g. Email support', max_length=200)),
                ('school_size_limit', models.PositiveIntegerField(blank=True, help_text='Maximum number of students', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('modules', models.ManyToManyField(blank=True, related_name='plans', to='products.module')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
