# Generated by Django 4.2.7 on 2026-03-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='tag_bn',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='module',
            name='tag_en',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
