# Generated by Django 4.2.7 on 2026-03-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_module_tag_bn_module_tag_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='stat_bn',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='module',
            name='stat_en',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
